{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"couldNotOpenDatabase"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/lighter\/lightererror\/errortype\/couldnotopendatabase(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/Lighter\/documentation\/Lighter\/LighterError\/ErrorType\/couldNotOpenDatabase(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"couldNotOpenDatabase"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"title":"LighterError.ErrorType.couldNotOpenDatabase(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:7Lighter0A5ErrorV0B4TypeO20couldNotOpenDatabaseyAE10Foundation3URLVcAEmF","modules":[{"name":"Lighter.swift for SQLite3"}]},"hierarchy":{"paths":[["doc:\/\/Lighter\/documentation\/Lighter","doc:\/\/Lighter\/documentation\/Lighter\/LighterError","doc:\/\/Lighter\/documentation\/Lighter\/LighterError\/ErrorType"]]},"references":{"doc://Lighter/documentation/Lighter/LighterError":{"role":"symbol","title":"LighterError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LighterError"}],"abstract":[{"type":"text","text":"An error that is thrown by Lighter database operations."}],"identifier":"doc:\/\/Lighter\/documentation\/Lighter\/LighterError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LighterError"}],"url":"\/documentation\/lighter\/lightererror"},"doc://Lighter/documentation/Lighter":{"role":"collection","title":"Lighter.swift for SQLite3","abstract":[{"type":"text","text":"Type-safe down to the schema. Very, "},{"type":"strong","inlineContent":[{"type":"text","text":"very"}]},{"type":"text","text":", fast. Dependency free."}],"identifier":"doc:\/\/Lighter\/documentation\/Lighter","kind":"symbol","type":"topic","url":"\/documentation\/lighter"},"doc://Lighter/documentation/Lighter/LighterError/ErrorType":{"role":"symbol","title":"LighterError.ErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorType"}],"abstract":[{"type":"text","text":"The kind of the error that happened within Lighter."}],"identifier":"doc:\/\/Lighter\/documentation\/Lighter\/LighterError\/ErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorType"}],"url":"\/documentation\/lighter\/lightererror\/errortype"},"doc://Lighter/documentation/Lighter/LighterError/ErrorType/couldNotOpenDatabase(_:)":{"role":"symbol","title":"LighterError.ErrorType.couldNotOpenDatabase(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"couldNotOpenDatabase"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/Lighter\/documentation\/Lighter\/LighterError\/ErrorType\/couldNotOpenDatabase(_:)","kind":"symbol","type":"topic","url":"\/documentation\/lighter\/lightererror\/errortype\/couldnotopendatabase(_:)"}}}